name: Metrics
on:
  # Update daily
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: noverse
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: nvgh-metrics.svg
          token: ${{ secrets.NV_TOKEN }}
          user: nohuto
          template: classic
          base: header, repositories
          base_indepth: yes
          config_order: base.header, introduction, base.repositories, languages, repositories, isocalendar, pagespeed, screenshot
          config_timezone: Europe/Berlin
          # Activity - Error
          #plugin_activity: yes
          #plugin_activity_days: 100
          #plugin_activity_filter: all
          #plugin_activity_limit: 5
          #plugin_activity_load: 1000
          #plugin_activity_visibility: public
          # Habits - Error
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 30
          plugin_habits_facts: yes
          plugin_habits_from: 1000
          plugin_habits_trim: yes
          plugin_habits_languages_limit: 8
          plugin_habits_languages_threshold: 0%
          # Introduction
          plugin_introduction: yes
          plugin_introduction_title: yes
          # Isocalendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          # Languages
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          # PageSpeed
          plugin_pagespeed: yes
          plugin_pagespeed_detailed: yes
          #plugin_pagespeed_screenshot: yes
          plugin_pagespeed_token: ${{ secrets.PAGESPEED }}
          plugin_pagespeed_url: https://nohuto.github.io/projects.html
          # Repositories
          plugin_repositories: yes
          plugin_repositories_order: pinned
          plugin_repositories_pinned: 8
          #repositories_forks: yes
          #  Screenshot
          #plugin_screenshot: yes
          #plugin_screenshot_background: yes
          #plugin_screenshot_mode: image
          #plugin_screenshot_selector: body
          #plugin_screenshot_wait: 60000
          #plugin_screenshot_title: Projects Page
          #plugin_screenshot_url: https://nohuto.github.io/projects.html

          retries: 5
          retries_delay: 1000

          #delay: 0
          #plugins_errors_fatal: no
          #debug: no
          #verify: no
